"""Emit paper/numbers.tex — every number the paper quotes, as a LaTeX macro.

The paper must not contain a hand-typed result. A number typed into prose is a
number that silently goes stale the next time the card is rebuilt, and this
project has already published one table it had to correct. So `main.tex` says
\\MeanR and never 0.906, and this script is the only thing allowed to decide
what \\MeanR is.

    python3 scripts/paper_numbers.py            # -> paper/numbers.tex

Anything the paper needs that is not derivable from card.json or
persona_depth.json does not belong in the paper.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Numeric macros are emitted as \newcommand so a missing one is a LaTeX error
# at build time rather than a blank in a PDF nobody re-reads.
HEADER = r"""% Generated by scripts/paper_numbers.py. Do not edit.
% Every result in main.tex resolves through these macros.
"""


def _cmd(name: str, value: str) -> str:
    # A TeX control sequence is letters only. A digit in the name does not
    # fail here -- it fails at compile time, inside numbers.tex, as
    # "Missing \begin{document}", which points nowhere near the real cause.
    # \PersonaAbovePoint3 cost one confusing build; refuse it at the source.
    if not name.isalpha():
        raise ValueError(
            f"illegal LaTeX macro name {name!r}: control sequences may contain "
            f"letters only (spell digits out, as _slug does)"
        )
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def _roster_sizes() -> tuple[dict[str, float], dict[str, str]]:
    """Parameter counts and families, read from the roster the sweep ran.

    A size table typed into this script is one more thing that can drift away
    from the models actually measured.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from nullcard.roster import SELF_HOSTED

    return ({m.hf_id: m.params_b for m in SELF_HOSTED},
            {m.hf_id: m.family for m in SELF_HOSTED})


def _slug(model: str) -> str:
    """A model id as a LaTeX-safe macro name: Qwen/Qwen3.5-0.8B -> QwenIIIVZeroEightB.

    LaTeX macro names admit letters only, so digits and punctuation are spelled
    out. Ugly, and the alternative is \\csname gymnastics in the paper itself.
    """
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    tail = model.split("/")[-1]
    return "".join(digits.get(c, c) for c in tail if c.isalnum())


def build(card: dict, personas: list[dict], length: dict | None = None,
          floor_decomp: dict | None = None, reasoning: dict | None = None,
          validity: list[dict] | None = None) -> str:
    tiles = [t for t in card["tiles"] if t["badge"] == "FLOOR_CORRECTED"]
    tiles.sort(key=lambda t: -t["raw_coherence"])
    out = [HEADER]

    n = len(tiles)
    mean_r = sum(t["raw_coherence"] for t in tiles) / n
    mean_f = sum(t["floor"] for t in tiles) / n
    out.append(_cmd("NModels", str(n)))
    out.append(_cmd("NCells", str(len(card["cells"]))))
    out.append(_cmd("NSplits", str(card["n_splits"])))
    out.append(_cmd("MeanR", f"{mean_r:.3f}"))
    out.append(_cmd("MeanFloor", f"{mean_f:.3f}"))
    out.append(_cmd("MeanResidual", f"{mean_r - mean_f:+.3f}"))
    out.append(_cmd("NClears", str(sum(1 for t in tiles if t.get("clears_floor")))))
    out.append(_cmd("NNegative", str(sum(1 for t in tiles if t["value"] < 0))))
    out.append(_cmd("BatterySHA", card["tiles"][0]["battery_sha256"][:16]))

    # Strength: the headline contrast. Restricted to models that are decisive
    # at all on real outcomes, because a model that never commits anywhere has
    # no ratio to report and would drag the mean toward a meaningless zero.
    dec = [(t["decisive_fraction"]["R"], t["decisive_fraction"]["N_minus"])
           for t in tiles if t["decisive_fraction"]["R"] > 0.02]
    out.append(_cmd("MeanDecisiveR", f"{100 * sum(a for a, _ in dec) / len(dec):.0f}"))
    out.append(_cmd("MeanDecisiveN", f"{100 * sum(b for _, b in dec) / len(dec):.1f}"))
    ratios = [a / b for a, b in dec if b > 0]
    out.append(_cmd("MedianDecisiveRatio",
                    f"{sorted(ratios)[len(ratios) // 2]:.0f}"))

    # Per-model, so a sentence naming a model cannot disagree with the table.
    for t in tiles:
        s = _slug(t["model"])
        out.append(_cmd(f"{s}R", f"{t['raw_coherence']:.3f}"))
        out.append(_cmd(f"{s}N", f"{t['floor']:.3f}"))
        out.append(_cmd(f"{s}Resid", f"{t['value']:+.3f}"))
        dnf = t.get("design_noise_floor")
        out.append(_cmd(f"{s}Floor", f"{dnf:.3f}" if dnf is not None else "n/a"))

    # P4, the pre-registered decisive prediction: does the FLOOR rise with
    # scale as fast as the signal? Computed here rather than eyeballed, and
    # only over one family with size as the sole variable.
    ladder = sorted(
        [t for t in tiles if t["model"].startswith("Qwen/Qwen3.5-")],
        key=lambda t: float(t["model"].split("-")[-1].rstrip("B")),
    )
    if len(ladder) >= 2:
        lo, hi = ladder[0], ladder[-1]
        out.append(_cmd("LadderSmall", lo["model"].split("/")[-1]))
        out.append(_cmd("LadderLarge", hi["model"].split("/")[-1]))
        out.append(_cmd("LadderRRise", f"{hi['raw_coherence'] - lo['raw_coherence']:+.3f}"))
        out.append(_cmd("LadderNRise", f"{hi['floor'] - lo['floor']:+.3f}"))
        out.append(_cmd("LadderResidFall", f"{hi['value'] - lo['value']:+.3f}"))

    # The pooled scale trend, reported WITH the decomposition that undercuts it.
    # r = -0.67 over nine models reads as a cross-family result until you split
    # it: it is carried by the one family where size is the only variable, and
    # among the other five there is nothing. Emitting both from the same code
    # makes it awkward to quote only the flattering half.
    sizes, fams = _roster_sizes()
    pts = [(sizes[t["model"]], t["value"], t["floor"], fams[t["model"]])
           for t in tiles if t["model"] in sizes]
    if len(pts) >= 4:
        import math

        def _corr(xs, ys):
            n = len(xs)
            mx, my = sum(xs) / n, sum(ys) / n
            sx = math.sqrt(sum((x - mx) ** 2 for x in xs))
            sy = math.sqrt(sum((y - my) ** 2 for y in ys))
            if sx == 0 or sy == 0:
                return float("nan")
            return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)

        lg = [math.log2(p[0]) for p in pts]
        out.append(_cmd("PooledSizeCorr", f"{_corr(lg, [p[1] for p in pts]):.2f}"))
        out.append(_cmd("PooledFloorCorr", f"{_corr(lg, [p[2] for p in pts]):+.2f}"))
        # The family carrying the pooled trend is the one with the most sizes.
        counts: dict[str, int] = {}
        for p in pts:
            counts[p[3]] = counts.get(p[3], 0) + 1
        ladder = max(counts, key=counts.get)
        inside = [p for p in pts if p[3] == ladder]
        outside = [p for p in pts if p[3] != ladder]
        out.append(_cmd("LadderFamily", ladder))
        out.append(_cmd("LadderNSizes", str(len(inside))))
        if len(inside) >= 3:
            out.append(_cmd("WithinFamilyCorr",
                            f"{_corr([math.log2(p[0]) for p in inside], [p[1] for p in inside]):.2f}"))
        if len(outside) >= 3:
            out.append(_cmd("OutsideFamilyCorr",
                            f"{_corr([math.log2(p[0]) for p in outside], [p[1] for p in outside]):.2f}"))
            out.append(_cmd("NOutsideFamily", str(len(outside))))

    if length is not None:
        al = length["arm_lengths"]
        out.append(_cmd("TokensR", f"{al['R']:.1f}"))
        out.append(_cmd("TokensNm", f"{al['N_minus']:.1f}"))
        out.append(_cmd("TokenInflation", f"{al['N_minus'] / al['R']:.1f}"))
        mb = length.get("matched_band")
        if mb and mb.get("mean_residual") is not None:
            out.append(_cmd("MatchedBandLo", f"{mb['band'][0]:.0f}"))
            out.append(_cmd("MatchedBandHi", f"{mb['band'][1]:.0f}"))
            out.append(_cmd("MatchedResidual", f"{mb['mean_residual']:+.3f}"))

    if floor_decomp is not None:
        sm = floor_decomp["summary"]
        for arm, tag in (("R", "Real"), ("N_minus", "Floor")):
            s = sm.get(arm) or {}
            if s.get("length_rule") is not None:
                out.append(_cmd(f"{tag}LengthRule", f"{s['length_rule']:.3f}"))
            if s.get("fit_on_length_tied") is not None:
                out.append(_cmd(f"{tag}TiedAcc", f"{s['fit_on_length_tied']:.3f}"))
            if s.get("fit") is not None:
                out.append(_cmd(f"{tag}DecompFit", f"{s['fit']:.3f}"))
        # The model whose invented ordering is MOST explained by length alone.
        # Named in the prose as the exception, so it is found rather than
        # remembered -- if the data changes, so does the sentence.
        cands = [(v["N_minus"]["length_rule"], m, v["N_minus"]["fit"])
                 for m, v in floor_decomp["per_model"].items()
                 if v.get("N_minus", {}).get("length_rule") is not None]
        if cands:
            rule, model, fit = max(cands)
            out.append(_cmd("MostLengthModel",
                            model.split("/")[-1].replace("_", r"\_")))
            out.append(_cmd("MostLengthRule", f"{rule:.3f}"))
            out.append(_cmd("MostLengthFit", f"{fit:.3f}"))

    # The second, discarded channel: how much probability mass leaves the answer
    # options when the outcomes stop meaning anything. Invisible to coherence,
    # which renormalises over A and B and so cannot see mass go elsewhere.
    import math as _m

    drops = [(t["mean_answer_mass"]["R"] - t["mean_answer_mass"]["N_minus"], t)
             for t in tiles]
    pos = sum(1 for d, _ in drops if d > 0)
    out.append(_cmd("NMassDrop", str(pos)))
    out.append(_cmd("MedianMassDrop",
                    f"{sorted(d for d, _ in drops)[len(drops) // 2]:+.3f}"))
    # Two-sided sign test: is a drop in this direction more than a coin flip?
    n_nz = sum(1 for d, _ in drops if d != 0)
    sign_p = min(1.0, 2 * sum(_m.comb(n_nz, k)
                              for k in range(pos, n_nz + 1)) / 2 ** n_nz)
    out.append(_cmd("MassDropSignP", f"{sign_p:.3f}"))
    big_d, big_t = max(drops)
    out.append(_cmd("ReasoningModel", big_t["model"].split("/")[-1]))
    out.append(_cmd("ReasoningMassDrop", f"{big_d:.3f}"))
    out.append(_cmd("ReasoningResid", f"{big_t['value']:+.3f}"))
    rest = [d for d, _ in drops if d != big_d]
    out.append(_cmd("MassDropExclReasoning", f"{sum(rest) / len(rest):+.3f}"))

    if reasoning is not None and reasoning.get("_summary"):
        out.append(_cmd("ResidShiftAnswered",
                        f"{reasoning['_summary']['mean_residual_shift']:+.3f}"))

    # The DIRECTIONAL persona test, and the control that qualifies it. Magnitude
    # said personas move wanting; direction says two thirds of that movement is
    # present on outcomes that mean nothing. Both numbers ship together.
    if validity:
        import statistics as _st
        real = [r["real_lc"] for r in validity if r.get("real_lc") is not None]
        exc = [r["excess_lc"] for r in validity if r.get("excess_lc") is not None]
        amb = [r["real_lc"] for r in validity
               if r["persona"] == "ambitious" and r.get("real_lc") is not None]
        cau = [r["real_lc"] for r in validity
               if r["persona"] == "cautious" and r.get("real_lc") is not None]
        ok = sum(1 for r in validity if r.get("real_lc") is not None
                 and (r["real_lc"] > 0) == (r["persona"] == "ambitious"))
        out.append(_cmd("PersonaSignCorrect", str(ok)))
        out.append(_cmd("PersonaSignTotal", str(len(real))))
        out.append(_cmd("PersonaSepReal", f"{_st.mean(amb) - _st.mean(cau):+.3f}"))
        inv_a = [r["invented_lc"] for r in validity
                 if r["persona"] == "ambitious" and r.get("invented_lc") is not None]
        inv_c = [r["invented_lc"] for r in validity
                 if r["persona"] == "cautious" and r.get("invented_lc") is not None]
        out.append(_cmd("PersonaSepInvented",
                        f"{_st.mean(inv_a) - _st.mean(inv_c):+.3f}"))
        out.append(_cmd("PersonaExcess", f"{_st.mean(exc):+.3f}"))
        out.append(_cmd("PersonaNonsenseShare",
                        f"{100 * (1 - _st.mean(exc) / _st.mean([abs(v) for v in real])):.0f}"))
        per: dict[str, list[float]] = {}
        for r in validity:
            if r.get("excess_lc") is not None:
                per.setdefault(r["model"], []).append(r["excess_lc"])
        keep = sorted(((sum(v) / len(v), m) for m, v in per.items()), reverse=True)
        out.append(_cmd("PersonaNRetain", str(sum(1 for e, _ in keep if e > 0.1))))
        out.append(_cmd("PersonaNModelsTested", str(len(keep))))
        out.append(_cmd("PersonaRetainTop", keep[0][1].split("/")[-1]))
        out.append(_cmd("PersonaRetainTopVal", f"{keep[0][0]:+.3f}"))

    if personas:
        vals = [r["floor_corrected"] for r in personas]
        out.append(_cmd("NPersonaCells", str(len(vals))))
        out.append(_cmd("NPersonaModels", str(len({r["model"] for r in personas}))))
        out.append(_cmd("PersonaAbovePointThree", str(sum(1 for v in vals if v > 0.3))))
        out.append(_cmd("PersonaMax", f"{max(vals):+.2f}"))
        out.append(_cmd("PersonaMin", f"{min(vals):+.2f}"))
        # D1 vs D2: the spread attributable to WHERE the trait sits, against
        # the spread attributable to WHICH trait it is. If the first is the
        # smaller, depth is not the interesting variable.
        def _spread_over(varying: str) -> float:
            """Mean within-group range when `varying` is the only thing that moves.

            Groups are keyed by everything *except* `varying`, so each group
            holds the same model under the same other factor and differs only
            in the one under test.
            """
            held = "depth" if varying == "persona" else "persona"
            groups: dict[tuple, list[float]] = {}
            for r in personas:
                groups.setdefault((r["model"], r[held]), []).append(r["floor_corrected"])
            return sum(max(v) - min(v) for v in groups.values()) / len(groups)

        out.append(_cmd("DepthSpread", f"{_spread_over('depth'):.3f}"))
        out.append(_cmd("PersonaSpread", f"{_spread_over('persona'):.3f}"))

    return "".join(out)


def build_table(card: dict) -> str:
    r"""Table 1 as a complete \input-able tabular.

    Generated for the same reason as the macros: a table maintained by hand
    beside a card that is rebuilt nightly diverges, and the divergence is
    invisible in a compiled PDF.

    The whole environment is emitted, not just the body rows, for two reasons.
    A file of bare rows ending in ``\\`` cannot be followed by ``\bottomrule``
    in the parent file --- ``\\`` scans ahead for its optional ``[dim]``
    argument, that scan runs off the end of the \input, and the rule is then
    read outside a row boundary and fails as "Misplaced \noalign" pointing at
    the wrong file. Emitting the environment also means the column
    specification lives in one place instead of being repeated, and kept in
    sync by hand, in both main.tex and slides.tex.
    """
    tiles = [t for t in card["tiles"] if t["badge"] == "FLOOR_CORRECTED"]
    tiles.sort(key=lambda t: -t["raw_coherence"])
    rows = []
    for t in tiles:
        dnf = t.get("design_noise_floor")
        if t.get("clears_floor") is None:
            clears = "--"
        elif not t["clears_floor"]:
            clears = "no"
        elif dnf is not None and dnf < 0.005:
            # A ratio against a near-zero denominator is a division artifact,
            # not a large effect; flag it instead of printing a big number.
            clears = r"$>$\,floor$^{*}$"
        else:
            clears = f"{t['floor_margin']:.1f}$\\times$"
        rows.append(
            f"\\texttt{{{t['model'].replace('_', r'\_')}}} & "
            f"{t['raw_coherence']:.3f} & {t['floor']:.3f} & {t['value']:+.3f} & "
            f"{(f'{dnf:.3f}' if dnf is not None else '--')} & {clears} & "
            f"{t['decisive_fraction']['R'] * 100:.1f}\\% & "
            f"{t['decisive_fraction']['N_minus'] * 100:.1f}\\%"
        )
    header = (r"model & R & N\textsuperscript{--} & R$-$N\textsuperscript{--}"
              r" & floor & clears & dec.\ R & dec.\ N\textsuperscript{--}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        "\\begin{tabular}{@{}lrrrrlrr@{}}\n"
        "\\toprule\n"
        f"{header} \\\\\n"
        "\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--card", default="card.json")
    ap.add_argument("--personas", default="site/persona_depth.json")
    ap.add_argument("--out", default="paper/numbers.tex")
    ap.add_argument("--table-out", default="paper/table_main.tex")
    ap.add_argument("--length", default="site/length_control.json")
    ap.add_argument("--floor-decomp", default="site/floor_decomposition.json")
    ap.add_argument("--reasoning", default="site/reasoning_effect.json")
    ap.add_argument("--validity", default="site/persona_validity.json")
    args = ap.parse_args()

    card = json.loads(Path(args.card).read_text())
    ppath = Path(args.personas)
    personas = json.loads(ppath.read_text()) if ppath.exists() else []

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lpath = Path(args.length)
    length = json.loads(lpath.read_text()) if lpath.exists() else None
    if length is None:
        print(f"  no length control at {lpath}; omitting those macros")
    fdpath = Path(args.floor_decomp)
    floor_decomp = json.loads(fdpath.read_text()) if fdpath.exists() else None
    rpath = Path(args.reasoning)
    reasoning = json.loads(rpath.read_text()) if rpath.exists() else None
    vpath = Path(args.validity)
    validity = json.loads(vpath.read_text()) if vpath.exists() else None
    text = build(card, personas, length, floor_decomp, reasoning, validity)
    out.write_text(text)
    print(f"wrote {out}  ({text.count('newcommand')} macros)")

    tout = Path(args.table_out)
    tout.write_text(build_table(card))
    print(f"wrote {tout}")


if __name__ == "__main__":
    main()
