"""Emit paper/numbers.tex — every number the paper quotes, as a LaTeX macro.

The paper must not contain a hand-typed result. A number typed into prose is a
number that silently goes stale the next time the card is rebuilt, and this
project has already published one table it had to correct. So `main.tex` says
\\MeanR and never 0.906, and this script is the only thing allowed to decide
what \\MeanR is.

    python3 scripts/paper_numbers.py            # -> paper/numbers.tex

Anything the paper needs that is not derivable from card.json or
persona_depth.json does not belong in the paper.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Numeric macros are emitted as \newcommand so a missing one is a LaTeX error
# at build time rather than a blank in a PDF nobody re-reads.
HEADER = r"""% Generated by scripts/paper_numbers.py. Do not edit.
% Every result in main.tex resolves through these macros.
"""


def _thousands(n: int) -> str:
    """LaTeX-safe thousands separator: 22436 -> 22{,}436.

    The braces stop TeX treating the comma as maths punctuation (which sets it
    with a trailing space), so this cannot be an inline f-string replace inside
    another f-string without brace-escaping bugs.
    """
    return f"{n:,}".replace(",", "{,}")


def _cmd(name: str, value: str) -> str:
    # A TeX control sequence is letters only. A digit in the name does not
    # fail here -- it fails at compile time, inside numbers.tex, as
    # "Missing \begin{document}", which points nowhere near the real cause.
    # \PersonaAbovePoint3 cost one confusing build; refuse it at the source.
    if not name.isalpha():
        raise ValueError(
            f"illegal LaTeX macro name {name!r}: control sequences may contain "
            f"letters only (spell digits out, as _slug does)"
        )
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def _roster_sizes() -> tuple[dict[str, float], dict[str, str]]:
    """Parameter counts and families, read from the roster the sweep ran.

    A size table typed into this script is one more thing that can drift away
    from the models actually measured.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from nullcard.roster import SELF_HOSTED

    return ({m.hf_id: m.params_b for m in SELF_HOSTED},
            {m.hf_id: m.family for m in SELF_HOSTED})


def _hosted_scoreability() -> dict[str, list]:
    """Which frontier models the first-token metric can read at all.

    `first_token_ok` in the roster is measured, not assumed: it records whether
    the model puts its forced choice in the first sampled token. Split three
    ways here because the failures are not the same kind of thing -- a model
    that spends its first token on a reasoning preamble is a limit of the
    metric, while an API that declines logprobs is a limit of the vendor, and
    the paper should not merge them into one number.

    Derived from the roster rather than typed into the paper, for the reason
    _roster_sizes gives: a hand-written "six of ten" goes stale the first time
    a hosted model is added.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from nullcard.roster import NEBIUS, scoreable_hosted

    return {
        "all": list(NEBIUS),
        "ok": scoreable_hosted(),
        "preamble": [m for m in NEBIUS if m.logprobs and not m.first_token_ok],
        "no_logprobs": [m for m in NEBIUS if not m.logprobs],
    }


def _tex(s: str) -> str:
    """Escape a model id for use as a macro VALUE.

    Macro names are constrained to letters by _cmd; values are not, but they
    still reach LaTeX verbatim. Nemotron-3_5-Lightning carries an underscore,
    which is a subscript in math mode and an error outside it.
    """
    return s.replace("\\", r"\textbackslash{}").replace("_", r"\_")


def _slug(model: str) -> str:
    """A model id as a LaTeX-safe macro name: Qwen/Qwen3.5-0.8B -> QwenIIIVZeroEightB.

    LaTeX macro names admit letters only, so digits and punctuation are spelled
    out. Ugly, and the alternative is \\csname gymnastics in the paper itself.
    """
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    tail = model.split("/")[-1]
    return "".join(digits.get(c, c) for c in tail if c.isalnum())


GENUINE, CONCEALED, VERBAL, UNRELATED = (
    "cautious", "cautious-concealed", "cautious-verbal", "ambitious")
# scripts/deception.py keys models as Org__Name; everything else in this repo
# uses Org/Name, and _slug splits on "/". Normalise once, at the boundary.
def _norm(model: str) -> str:
    return model.replace("__", "/")


def build(card: dict, personas: list[dict], length: dict | None = None,
          floor_decomp: dict | None = None, reasoning: dict | None = None,
          validity: list[dict] | None = None,
          detector: dict | None = None, stated: list[dict] | None = None,
          stated_base: list[dict] | None = None,
          revealed: dict | None = None,
          neutral: dict | None = None,
          rendered: dict | None = None,
          comply: dict | None = None,
          mixed: dict | None = None,
          surface: dict | None = None,
          attrition: dict | None = None,
          hosted: dict | None = None,
          avoidance: dict | None = None,
          contrast: dict | None = None) -> str:
    tiles = [t for t in card["tiles"] if t["badge"] == "FLOOR_CORRECTED"]
    tiles.sort(key=lambda t: -t["raw_coherence"])
    out = [HEADER]

    n = len(tiles)
    mean_r = sum(t["raw_coherence"] for t in tiles) / n
    mean_f = sum(t["floor"] for t in tiles) / n
    out.append(_cmd("NModels", str(n)))
    out.append(_cmd("NCells", str(len(card["cells"]))))
    out.append(_cmd("NSplits", str(card["n_splits"])))
    # Design replicates are not train/test splits, and the two get conflated:
    # NSplits re-splits one design, NDesignReps counts independent designs
    # (a different outcome subsample and pair set each time). The design floor
    # rests on the second, so the ledger must be able to name it.
    reps = {t.get("n_design_replicates", 1) for t in tiles}
    out.append(_cmd("NDesignReps", str(min(reps))))
    out.append(_cmd("MeanR", f"{mean_r:.3f}"))
    out.append(_cmd("MeanFloor", f"{mean_f:.3f}"))
    out.append(_cmd("MeanResidual", f"{mean_r - mean_f:+.3f}"))
    out.append(_cmd("NClears", str(sum(1 for t in tiles if t.get("clears_floor")))))
    out.append(_cmd("NNegative", str(sum(1 for t in tiles if t["value"] < 0))))
    out.append(_cmd("BatterySHA", card["tiles"][0]["battery_sha256"][:16]))
    # Families, because "nine models" and "nine models from one family" are
    # different studies and the abstract has to say which.
    out.append(_cmd("NFamilies", str(len({t["model"].split("/")[0] for t in tiles}))))

    # The hosted arm is reported beside the self-hosted ladder and never inside
    # its mean: different provider, different harness_hash by construction.
    if hosted and hosted.get("tiles"):
        ht = [t for t in hosted["tiles"] if t.get("badge") == "FLOOR_CORRECTED"]
        if ht:
            out.append(_cmd("NHosted", str(len(ht))))
            biggest = max(ht, key=lambda t: t.get("value", 0))
            out.append(_cmd("LadderHosted", biggest["model"].split("/")[-1]))
            out.append(_cmd("HostedResidual", f"{biggest['value']:+.4f}"))

    # The MIXED arm (P13-P15): where meaninglessness sits on the real scale.
    if mixed and mixed.get("models"):
        ms = mixed["models"]
        out.append(_cmd("MixNModels", str(len(ms))))
        lc = [m["corr_utility_prefer_real_length_controlled"] for m in ms
              if "corr_utility_prefer_real_length_controlled" in m]
        if lc:
            out.append(_cmd("MixCorrLo", f"{min(lc):+.2f}"))
            out.append(_cmd("MixCorrHi", f"{max(lc):+.2f}"))
        out.append(_cmd("MixPreferRealLo",
                        f"{min(m['mean_prefer_real'] for m in ms):.3f}"))
        out.append(_cmd("MixPreferRealHi",
                        f"{max(m['mean_prefer_real'] for m in ms):.3f}"))
        out.append(_cmd("MixNBelowHalf",
                        str(sum(m["n_pairs_below_half"] for m in ms))))
        out.append(_cmd("MixNPairsTotal", f'{sum(m["n_pairs"] for m in ms):,}'.replace(",", "{,}")))
        out.append(_cmd("MixNBelowRange",
                        str(sum(1 for m in ms if m["indifference_below_range"]))))
        # The harm-beyond-utility test, reported with its held-out count so the
        # verdict cannot be quoted without the n it rests on.
        h = mixed.get("harm")
        if h:
            out.append(_cmd("HarmNHeldOut", str(h["n_held_out"])))
            out.append(_cmd("HarmNSupporting",
                            str(h["n_held_out_below_threshold"])))
            out.append(_cmd("HarmMeanCorr", f"{h['mean_corr_held_out']:+.3f}"))
            out.append(_cmd("HarmNContaminated",
                            str(len(h["read_before_hypothesis"]))))
            out.append(_cmd("HarmVerdict",
                            "supported" if h["n_held_out_below_threshold"]
                            >= max(2, int(0.7 * h["n_held_out"]))
                            else "not supported"))

    # The instruction-following gate (P12). Reported with BOTH criteria,
    # because the registered one and the one the gate needs disagree in
    # opposite directions on two different models.
    if comply is not None:
        out.append(_cmd("ComplyNModels", str(comply["n_models"])))
        out.append(_cmd("ComplyNObey", str(comply["n_complying"])))
        out.append(_cmd("ComplyNRegister", str(comply["n_registering"])))
        out.append(_cmd("ComplyNBoth", str(comply["n_both"])))
        refuser = next((r for r in comply["rows"]
                        if r["registers"] and not r["complies"]), None)
        if refuser:
            out.append(_cmd("ComplyRefuser", refuser["model"].split("/")[-1]))
            out.append(_cmd("ComplyRefuserBase", f"{refuser['baseline_mean_p_a']:.3f}"))
            out.append(_cmd("ComplyRefuserAfter", f"{refuser['mean_p_a']:.3f}"))
        trivial = next((r for r in comply["rows"]
                        if r["complies"] and not r["registers"]), None)
        if trivial:
            out.append(_cmd("ComplyTrivial", trivial["model"].split("/")[-1]))
            out.append(_cmd("ComplyTrivialBase", f"{trivial['baseline_mean_p_a']:.3f}"))
        out.append(_cmd("ComplyNSlotReaches",
                        str(sum(1 for r in comply["rows"]
                                if r.get("slot_reaches_decision")))))
        # The direction control, which is what rules the harness explanation
        # in or out for a model that failed to obey.
        for d in comply.get("direction_control", []):
            if d["verdict"].startswith("SELECTIVE"):
                out.append(_cmd("DirSelective", d["model"].split("/")[-1]))
                out.append(_cmd("DirSelectiveWith", f"{d['p_a_under_answer_a']:.3f}"))
                out.append(_cmd("DirSelectiveAgainst", f"{d['p_a_under_answer_b']:.3f}"))
        out.append(_cmd("DirNObeyBoth",
                        str(sum(1 for d in comply.get("direction_control", [])
                                if d["verdict"].startswith("obeys both")))))
        pi = next((r for r in comply["rows"]
                   if r.get("persona_displacement") is not None
                   and r.get("directive_displacement") is not None
                   and r["directive_displacement"] > 3 * r["persona_displacement"]), None)
        if pi:
            out.append(_cmd("PersonaInertModel", pi["model"].split("/")[-1]))
            out.append(_cmd("PersonaInertPersona", f"{pi['persona_displacement']:.3f}"))
            out.append(_cmd("PersonaInertDirective", f"{pi['directive_displacement']:.3f}"))

    # The harness itself, as measured rather than as intended. The sweep sends
    # no system message at D0 and records system_prompt: None; some chat
    # templates supply one anyway. These macros exist so the limitation is
    # stated in the paper with numbers that update when the roster does --
    # a hand-typed "two models" would go stale the first time one is added.
    if rendered is not None:
        inj = sorted(m for m, c in rendered.get("models", {}).items()
                     if c.get("D0", {}).get("injects_unrequested_system_text"))
        dated = sorted(m for m, c in rendered.get("models", {}).items()
                       if any(v.get("injects_current_date") for v in c.values()))
        out.append(_cmd("HarnessNRendered", str(rendered.get("n_verified", 0))))
        out.append(_cmd("HarnessNInjecting", str(len(inj))))
        out.append(_cmd("HarnessNClean",
                        str(rendered.get("n_verified", 0) - len(inj))))
        out.append(_cmd("HarnessNDated", str(len(dated))))
        if inj:
            out.append(_cmd("HarnessInjectingModels",
                            ", ".join(m.split("/")[-1] for m in inj)))
        if dated:
            out.append(_cmd("HarnessDatedModel", dated[0].split("/")[-1]))
        # Whether the injection can be suppressed by sending our own system
        # message. A defect that cannot be fixed at the prompt level is a
        # different kind of limitation from one that can, and the paper has to
        # say which it has.
        eqm = rendered.get("equalisable", {})
        fixable = sorted(m for m in inj if eqm.get(m) is True)
        stuck = sorted(m for m in inj if eqm.get(m) is False)
        out.append(_cmd("HarnessNFixable", str(len(fixable))))
        out.append(_cmd("HarnessNStuck", str(len(stuck))))
        if stuck:
            out.append(_cmd("HarnessStuckModel", stuck[0].split("/")[-1]))

    # What the metric can read at all. This is a limitation of first-token
    # forced choice, not of this harness: most of the frontier roster cannot be
    # scored by it, and the measurement is already done. It also bounds our own
    # claims -- the models we report are the models that COULD be scored, which
    # is a selection on output format and not a random sample of the frontier.
    sc = _hosted_scoreability()
    n_unscoreable = len(sc["preamble"]) + len(sc["no_logprobs"])
    out.append(_cmd("HostedNTotal", str(len(sc["all"]))))
    out.append(_cmd("HostedNScoreable", str(len(sc["ok"]))))
    out.append(_cmd("HostedNUnscoreable", str(n_unscoreable)))
    out.append(_cmd("HostedNPreamble", str(len(sc["preamble"]))))
    out.append(_cmd("HostedNNoLogprobs", str(len(sc["no_logprobs"]))))
    if sc["no_logprobs"]:
        out.append(_cmd("HostedNoLogprobsModel",
                        _tex(sc["no_logprobs"][0].api_id.split("/")[-1])))
    out.append(_cmd("HostedScoreableModels", ", ".join(
        _tex(m.api_id.split("/")[-1]) for m in sc["ok"])))
    out.append(_cmd("HostedUnscoreableModels", ", ".join(
        _tex(m.api_id.split("/")[-1])
        for m in sc["preamble"] + sc["no_logprobs"])))

    # The remedy this paper predicted, measured. sec:limits used to assert that
    # a prefill variant "would recover them" -- all of the preamble-blocked
    # models -- on no evidence beyond the mechanism sounding right. It recovers
    # some. These macros exist so the sentence states the measurement, and so it
    # restates itself if the probe is ever re-run against a changed roster.
    pf_path = Path("site/hosted_scoreability_prefill.json")
    if pf_path.exists():
        pf = json.loads(pf_path.read_text())
        rec = sorted(m for m, v in pf.items() if v.get("first_token_scoreable"))
        unrec = sorted(m for m, v in pf.items()
                       if not v.get("first_token_scoreable"))
        out.append(_cmd("PrefillNProbed", str(len(pf))))
        out.append(_cmd("PrefillNRecovered", str(len(rec))))
        out.append(_cmd("PrefillNUnrecovered", str(len(unrec))))
        out.append(_cmd("PrefillRecoveredModels", ", ".join(
            _tex(m.split("/")[-1]) for m in rec)))
        out.append(_cmd("PrefillUnrecoveredModels", ", ".join(
            _tex(m.split("/")[-1]) for m in unrec)))
        # n per model is small (a handful of pairs), so the paper must say so
        # rather than let a bare 2-of-5 read as a settled rate.
        out.append(_cmd("PrefillNPairs",
                        str(min(v.get("n", 0) for v in pf.values()))))
        if rec:
            out.append(_cmd("PrefillBestMass",
                            f"{max(pf[m]['mean_answer_mass'] for m in rec):.3f}"))
            out.append(_cmd("PrefillWorstRecoveredMass",
                            f"{min(pf[m]['mean_answer_mass'] for m in rec):.3f}"))
        if unrec:
            out.append(_cmd("PrefillBestUnrecoveredMass",
                            f"{max(pf[m]['mean_answer_mass'] for m in unrec):.3f}"))

    # The frontier check. Read from card_hosted.json rather than card.json
    # because the hosted tree is deliberately not pooled with the self-hosted
    # one -- different serving stack, so these macros exist to be quoted BESIDE
    # the local ladder with the difference stated, never inside its mean.
    ch_path = Path("site/card_hosted.json")
    if ch_path.exists():
        ch = json.loads(ch_path.read_text())
        # Per model, keyed by slug. No "largest hosted model" macro: HostedModel
        # carries no parameter count, and half the roster's sizes are not
        # public, so any such macro would rest on a number we invented. The
        # prose names the model it is discussing instead.
        scored = [t for t in ch["tiles"]
                  if t.get("floor") is not None and t.get("value") is not None]
        for t in scored:
            s = _slug(t["model"])
            out.append(_cmd(f"{s}HostR", f"{t['raw_coherence']:.3f}"))
            out.append(_cmd(f"{s}HostN", f"{t['floor']:.3f}"))
            out.append(_cmd(f"{s}HostResid", f"{t['value']:+.3f}"))
            out.append(_cmd(f"{s}HostDecR",
                            f"{100 * t['decisive_fraction']['R']:.0f}"))
            out.append(_cmd(f"{s}HostDecN",
                            f"{100 * t['decisive_fraction']['N_minus']:.0f}"))
            out.append(_cmd(f"{s}HostReps", str(t.get("n_design_replicates", 1))))
        out.append(_cmd("HostedNScored", str(len(scored))))

    # The persona indicators against their denominator. Emitted because the
    # magnitude claim (persona-displacement) was established against the bare
    # baseline, which differs from a persona cell by two things at once -- a
    # trait, and a block of added text. These macros carry the control that
    # separates them, including the self-check it FAILS, so the paper cannot
    # quote the flattering half alone.
    pd_path = Path("site/persona_denominator.json")
    if pd_path.exists():
        pd = json.loads(pd_path.read_text())
        for arm, tag in (("R", "R"), ("N_minus", "N")):
            c = pd["controls"][arm]
            out.append(_cmd(f"PdNegMag{tag}", f"{c['negative_magnitude_mean']:.2f}"))
            out.append(_cmd(f"PdNegMagMax{tag}", f"{c['negative_magnitude_max']:.2f}"))
            out.append(_cmd(f"PdNegDir{tag}", f"{c['negative_direction']:+.3f}"))
            out.append(_cmd(f"PdSelfDir{tag}", f"{c['self_check_direction']:+.3f}"))
            out.append(_cmd(f"PdShuffleDir{tag}",
                            f"{c['shuffle_direction_mean']:+.3f}"))
            out.append(_cmd(f"PdClearing{tag}",
                            f"{100 * c['positives_clearing_negative']:.0f}"))
            out.append(_cmd(f"PdNPositive{tag}", str(c["n_positive_cells"])))
            out.append(_cmd(f"PdNNegative{tag}", str(c["n_negative"])))
        ranked = [r for r in pd["conditions"]
                  if r["floor_corrected_direction"] is not None]
        if ranked:
            best, worst = ranked[0], ranked[-1]
            out.append(_cmd("PdBestCondition", _tex(best["condition"])))
            out.append(_cmd("PdBestFloorCorr",
                            f"{best['floor_corrected_direction']:.3f}"))
            out.append(_cmd("PdBestDirReal", f"{best['direction_real']:+.3f}"))
            out.append(_cmd("PdWorstCondition", _tex(worst["condition"])))
            out.append(_cmd("PdWorstFloorCorr",
                            f"{worst['floor_corrected_direction']:.3f}"))
            out.append(_cmd("PdNRanked", str(len(ranked))))
            # The reversal: the condition with the LARGEST raw direction
            # agreement, which is not the best marker.
            loud = max(ranked, key=lambda r: r["direction_real"])
            out.append(_cmd("PdLoudestCondition", _tex(loud["condition"])))
            out.append(_cmd("PdLoudestDirReal", f"{loud['direction_real']:+.3f}"))
            out.append(_cmd("PdLoudestFloorCorr",
                            f"{loud['floor_corrected_direction']:.3f}"))
            out.append(_cmd("PdNModelsPerCondition", str(best["n_models_real"])))

    # Track 6, the borrowed instrument. Emitted so the slides and sec:persona
    # can state a falsified pre-registered test with its actual numbers instead
    # of hedging qualitatively -- a registered test reported without the figure
    # it missed is not really reported.
    sch_path = Path("site/schwartz.json")
    if sch_path.exists():
        sch = json.loads(sch_path.read_text())
        sm = sch.get("summary", {})
        if sm:
            out.append(_cmd("SchNModels", str(sm["n_common"])))
            out.append(_cmd("SchNModelsAll", str(sm["R_all_models"]["n"])))
            out.append(_cmd("SchThreshold",
                            f"{sch['registered_threshold']:+.1f}"))
            out.append(_cmd("SchOpposedRAll",
                            f"{sm['R_all_models']['mean_opposed']:+.3f}"))
            for arm, tag in (("R", "R"), ("N_minus", "N")):
                a = sm[arm]
                out.append(_cmd(f"SchOpposed{tag}", f"{a['mean_opposed']:+.3f}"))
                out.append(_cmd(f"SchCross{tag}", f"{a['mean_cross_axis']:+.3f}"))
                out.append(_cmd(f"SchGap{tag}", f"{a['gap']:+.3f}"))
                out.append(_cmd(f"SchBelow{tag}", str(a["n_below_cross_axis"])))
            # 8 of 8: the exploratory contrast, counted across both arms.
            out.append(_cmd("SchBelowTotal",
                            str(sm["R"]["n_below_cross_axis"]
                                + sm["N_minus"]["n_below_cross_axis"])))
            out.append(_cmd("SchBelowDenom",
                            str(sm["R"]["n"] + sm["N_minus"]["n"])))
            if sch.get("dropped_from_comparison"):
                out.append(_cmd("SchDropped", _tex(
                    sch["dropped_from_comparison"][0].split("/")[-1])))

    # Answer-mass collapse: a model-level quantity that reads as an item-level
    # one until you ask whether the item ranking replicates. Emitted from
    # site/mass_collapse.json so the reliability number and the enrichment it
    # disqualifies cannot be quoted from different runs.
    mc_path = Path("site/mass_collapse.json")
    if mc_path.exists():
        mc = json.loads(mc_path.read_text())
        rel, enr = mc["reliability"], mc["enrichment"]
        per = rel["per_model"]
        out.append(_cmd("CollapseNModels", str(mc["n_models"])))
        out.append(_cmd("CollapseNItems", str(rel["n_items"])))
        out.append(_cmd("CollapseNSeeds",
                        str(min(v["n_seeds"] for v in per.values()))))
        out.append(_cmd("CollapseItemR", f"{rel['mean_item_r']:+.4f}"))
        out.append(_cmd("CollapseMassSD", f"{rel['max_mass_sd']:.4f}"))
        out.append(_cmd("CollapseTopK", str(enr["top_k"])))
        out.append(_cmd("CollapseObserved", f"{100 * enr['observed']:.0f}"))
        out.append(_cmd("CollapseChance", f"{100 * enr['pair_chance_rate']:.0f}"))
        out.append(_cmd("CollapseEnrich", f"{enr['enrichment']:.1f}"))
        # The recipe-not-scale contrast, named so prose cannot invert it: the
        # worst collapser against the SMALLEST model, which is not the same one.
        worst = min(per.items(), key=lambda kv: kv[1]["mean_mass"])
        clean = sorted(m for m, v in per.items() if v["mean_mass"] >= 1.0)
        out.append(_cmd("CollapseWorstModel", _tex(worst[0].split("/")[-1])))
        out.append(_cmd("CollapseWorstMass", f"{worst[1]['mean_mass']:.4f}"))
        out.append(_cmd("CollapseNClean", str(len(clean))))
        out.append(_cmd("CollapseCleanModels", ", ".join(
            _tex(m.split("/")[-1]) for m in clean)))
        smallest = "Qwen/Qwen3.5-0.8B"
        if smallest in per:
            out.append(_cmd("CollapseSmallestModel",
                            _tex(smallest.split("/")[-1])))
            out.append(_cmd("CollapseSmallestMass",
                            f"{per[smallest]['mean_mass']:.4f}"))

    # Strength: the headline contrast. Restricted to models that are decisive
    # at all on real outcomes, because a model that never commits anywhere has
    # no ratio to report and would drag the mean toward a meaningless zero.
    dec = [(t["decisive_fraction"]["R"], t["decisive_fraction"]["N_minus"])
           for t in tiles if t["decisive_fraction"]["R"] > 0.02]
    out.append(_cmd("MeanDecisiveR", f"{100 * sum(a for a, _ in dec) / len(dec):.0f}"))
    out.append(_cmd("MeanDecisiveN", f"{100 * sum(b for _, b in dec) / len(dec):.1f}"))
    ratios = [a / b for a, b in dec if b > 0]
    out.append(_cmd("MedianDecisiveRatio",
                    f"{sorted(ratios)[len(ratios) // 2]:.0f}"))

    # Per-model, so a sentence naming a model cannot disagree with the table.
    for t in tiles:
        s = _slug(t["model"])
        out.append(_cmd(f"{s}R", f"{t['raw_coherence']:.3f}"))
        out.append(_cmd(f"{s}N", f"{t['floor']:.3f}"))
        out.append(_cmd(f"{s}Resid", f"{t['value']:+.3f}"))
        dnf = t.get("design_noise_floor")
        out.append(_cmd(f"{s}Floor", f"{dnf:.3f}" if dnf is not None else "n/a"))

    # P4, the pre-registered decisive prediction: does the FLOOR rise with
    # scale as fast as the signal? Computed here rather than eyeballed, and
    # only over one family with size as the sole variable.
    ladder = sorted(
        [t for t in tiles if t["model"].startswith("Qwen/Qwen3.5-")],
        key=lambda t: float(t["model"].split("-")[-1].rstrip("B")),
    )
    if len(ladder) >= 2:
        lo, hi = ladder[0], ladder[-1]
        out.append(_cmd("LadderSmall", lo["model"].split("/")[-1]))
        out.append(_cmd("LadderLarge", hi["model"].split("/")[-1]))
        out.append(_cmd("LadderRRise", f"{hi['raw_coherence'] - lo['raw_coherence']:+.3f}"))
        out.append(_cmd("LadderNRise", f"{hi['floor'] - lo['floor']:+.3f}"))
        out.append(_cmd("LadderResidFall", f"{hi['value'] - lo['value']:+.3f}"))

    # The pooled scale trend, reported WITH the decomposition that undercuts it.
    # r = -0.67 over nine models reads as a cross-family result until you split
    # it: it is carried by the one family where size is the only variable, and
    # among the other five there is nothing. Emitting both from the same code
    # makes it awkward to quote only the flattering half.
    sizes, fams = _roster_sizes()
    pts = [(sizes[t["model"]], t["value"], t["floor"], fams[t["model"]])
           for t in tiles if t["model"] in sizes]
    if len(pts) >= 4:
        import math

        def _corr(xs, ys):
            n = len(xs)
            mx, my = sum(xs) / n, sum(ys) / n
            sx = math.sqrt(sum((x - mx) ** 2 for x in xs))
            sy = math.sqrt(sum((y - my) ** 2 for y in ys))
            if sx == 0 or sy == 0:
                return float("nan")
            return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)

        lg = [math.log2(p[0]) for p in pts]
        out.append(_cmd("PooledSizeCorr", f"{_corr(lg, [p[1] for p in pts]):.2f}"))
        out.append(_cmd("PooledFloorCorr", f"{_corr(lg, [p[2] for p in pts]):+.2f}"))
        # The family carrying the pooled trend is the one with the most sizes.
        counts: dict[str, int] = {}
        for p in pts:
            counts[p[3]] = counts.get(p[3], 0) + 1
        ladder = max(counts, key=counts.get)
        inside = [p for p in pts if p[3] == ladder]
        outside = [p for p in pts if p[3] != ladder]
        out.append(_cmd("LadderFamily", ladder))
        out.append(_cmd("LadderNSizes", str(len(inside))))
        # How many families could carry a within-family correlation at all.
        # The scaling claim rests on this being small; it must be derived, not
        # asserted, because "one family" is the claim's whole limitation.
        out.append(_cmd("LadderNFamilies",
                        str(sum(1 for c in counts.values() if c >= 3))))
        if len(inside) >= 3:
            out.append(_cmd("WithinFamilyCorr",
                            f"{_corr([math.log2(p[0]) for p in inside], [p[1] for p in inside]):.2f}"))
        if len(outside) >= 3:
            out.append(_cmd("OutsideFamilyCorr",
                            f"{_corr([math.log2(p[0]) for p in outside], [p[1] for p in outside]):.2f}"))
            out.append(_cmd("NOutsideFamily", str(len(outside))))

    if length is not None:
        al = length["arm_lengths"]
        out.append(_cmd("TokensR", f"{al['R']:.1f}"))
        out.append(_cmd("TokensNm", f"{al['N_minus']:.1f}"))
        out.append(_cmd("TokenInflation", f"{al['N_minus'] / al['R']:.1f}"))
        mb = length.get("matched_band")
        if mb and mb.get("mean_residual") is not None:
            out.append(_cmd("MatchedBandLo", f"{mb['band'][0]:.0f}"))
            out.append(_cmd("MatchedBandHi", f"{mb['band'][1]:.0f}"))
            out.append(_cmd("MatchedResidual", f"{mb['mean_residual']:+.3f}"))

    if floor_decomp is not None:
        sm = floor_decomp["summary"]
        for arm, tag in (("R", "Real"), ("N_minus", "Floor")):
            s = sm.get(arm) or {}
            if s.get("length_rule") is not None:
                out.append(_cmd(f"{tag}LengthRule", f"{s['length_rule']:.3f}"))
            if s.get("fit_on_length_tied") is not None:
                out.append(_cmd(f"{tag}TiedAcc", f"{s['fit_on_length_tied']:.3f}"))
            if s.get("fit") is not None:
                out.append(_cmd(f"{tag}DecompFit", f"{s['fit']:.3f}"))
        # The model whose invented ordering is MOST explained by length alone.
        # Named in the prose as the exception, so it is found rather than
        # remembered -- if the data changes, so does the sentence.
        cands = [(v["N_minus"]["length_rule"], m, v["N_minus"]["fit"])
                 for m, v in floor_decomp["per_model"].items()
                 if v.get("N_minus", {}).get("length_rule") is not None]
        if cands:
            rule, model, fit = max(cands)
            out.append(_cmd("MostLengthModel",
                            model.split("/")[-1].replace("_", r"\_")))
            out.append(_cmd("MostLengthRule", f"{rule:.3f}"))
            out.append(_cmd("MostLengthFit", f"{fit:.3f}"))

    # The second, discarded channel: how much probability mass leaves the answer
    # options when the outcomes stop meaning anything. Invisible to coherence,
    # which renormalises over A and B and so cannot see mass go elsewhere.
    import math as _m

    drops = [(t["mean_answer_mass"]["R"] - t["mean_answer_mass"]["N_minus"], t)
             for t in tiles]
    pos = sum(1 for d, _ in drops if d > 0)
    out.append(_cmd("NMassDrop", str(pos)))
    out.append(_cmd("MedianMassDrop",
                    f"{sorted(d for d, _ in drops)[len(drops) // 2]:+.3f}"))
    # Two-sided sign test: is a drop in this direction more than a coin flip?
    n_nz = sum(1 for d, _ in drops if d != 0)
    sign_p = min(1.0, 2 * sum(_m.comb(n_nz, k)
                              for k in range(pos, n_nz + 1)) / 2 ** n_nz)
    out.append(_cmd("MassDropSignP", f"{sign_p:.3f}"))
    big_d, big_t = max(drops)
    out.append(_cmd("ReasoningModel", big_t["model"].split("/")[-1]))
    out.append(_cmd("ReasoningMassDrop", f"{big_d:.3f}"))
    out.append(_cmd("ReasoningResid", f"{big_t['value']:+.3f}"))
    rest = [d for d, _ in drops if d != big_d]
    out.append(_cmd("MassDropExclReasoning", f"{sum(rest) / len(rest):+.3f}"))

    if reasoning is not None and reasoning.get("_summary"):
        out.append(_cmd("ResidShiftAnswered",
                        f"{reasoning['_summary']['mean_residual_shift']:+.3f}"))

    # The DIRECTIONAL persona test, and the control that qualifies it. Magnitude
    # said personas move wanting; direction says two thirds of that movement is
    # present on outcomes that mean nothing. Both numbers ship together.
    if validity:
        import statistics as _st
        real = [r["real_lc"] for r in validity if r.get("real_lc") is not None]
        exc = [r["excess_lc"] for r in validity if r.get("excess_lc") is not None]
        amb = [r["real_lc"] for r in validity
               if r["persona"] == "ambitious" and r.get("real_lc") is not None]
        cau = [r["real_lc"] for r in validity
               if r["persona"] == "cautious" and r.get("real_lc") is not None]
        ok = sum(1 for r in validity if r.get("real_lc") is not None
                 and (r["real_lc"] > 0) == (r["persona"] == "ambitious"))
        out.append(_cmd("PersonaSignCorrect", str(ok)))
        out.append(_cmd("PersonaSignTotal", str(len(real))))
        out.append(_cmd("PersonaSepReal", f"{_st.mean(amb) - _st.mean(cau):+.3f}"))
        inv_a = [r["invented_lc"] for r in validity
                 if r["persona"] == "ambitious" and r.get("invented_lc") is not None]
        inv_c = [r["invented_lc"] for r in validity
                 if r["persona"] == "cautious" and r.get("invented_lc") is not None]
        out.append(_cmd("PersonaSepInvented",
                        f"{_st.mean(inv_a) - _st.mean(inv_c):+.3f}"))
        out.append(_cmd("PersonaExcess", f"{_st.mean(exc):+.3f}"))
        out.append(_cmd("PersonaNonsenseShare",
                        f"{100 * (1 - _st.mean(exc) / _st.mean([abs(v) for v in real])):.0f}"))
        per: dict[str, list[float]] = {}
        for r in validity:
            if r.get("excess_lc") is not None:
                per.setdefault(r["model"], []).append(r["excess_lc"])
        keep = sorted(((sum(v) / len(v), m) for m, v in per.items()), reverse=True)
        out.append(_cmd("PersonaNRetain", str(sum(1 for e, _ in keep if e > 0.1))))
        out.append(_cmd("PersonaNModelsTested", str(len(keep))))
        out.append(_cmd("PersonaRetainTop", keep[0][1].split("/")[-1]))
        out.append(_cmd("PersonaRetainTopVal", f"{keep[0][0]:+.3f}"))

    # The detector framing: how well each channel of the SAME forward pass
    # separates real outcomes from nonsense. The kept channel against the
    # discarded ones is the whole argument in two numbers.
    if detector:
        import statistics as _st
        per = detector["per_model"]
        names = [k for k in next(iter(per.values())) if k != "n_matched_pairs"]
        def _mean(name, field="separation"):
            v = [e[name][field] for e in per.values() if name in e]
            return _st.mean(v) if v else None
        kept = next(n for n in names if "[KEPT]" in n)
        out.append(_cmd("DetKeptAuroc", f"{_mean(kept):.3f}"))
        out.append(_cmd("DetKeptTPR", f"{100 * _mean(kept, 'tpr_at_fpr'):.0f}"))
        disc = [(n, _mean(n)) for n in names if "discarded" in n]
        best, bv = max(disc, key=lambda kv: kv[1])
        out.append(_cmd("DetBestName", best.split("  ")[0]))
        out.append(_cmd("DetBestAuroc", f"{bv:.3f}"))
        out.append(_cmd("DetBestTPR", f"{100 * _mean(best, 'tpr_at_fpr'):.0f}"))
        out.append(_cmd("DetFPR", f"{100 * detector['fpr']:.0f}"))
        out.append(_cmd("DetNModels", str(len(per))))
        # The model panel B of the detector figure singles out. Read from the
        # detector's own output rather than chosen here, so the caption cannot
        # name a different model than the figure draws.
        if detector.get("showcase_model"):
            sm = detector["showcase_model"]
            out.append(_cmd("DetShowcase", sm.split("/")[-1]))
            e = per[sm]
            kept_ch = next(n for n in e if "[KEPT]" in n)
            best_ch = max((n for n in e if "discarded" in n),
                          key=lambda n: e[n]["separation"])
            out.append(_cmd("DetShowcaseKept", f"{e[kept_ch]['separation']:.2f}"))
            out.append(_cmd("DetShowcaseBest", f"{e[best_ch]['separation']:.2f}"))
        best_model = max(((e[best]["separation"], m) for m, e in per.items()
                          if best in e), default=(None, None))
        if best_model[1]:
            out.append(_cmd("DetBestModel", best_model[1].split("/")[-1]))
            out.append(_cmd("DetBestModelAuroc", f"{best_model[0]:.3f}"))

    # Track 3. A persona carries a trait AND a directive about it -- have it,
    # hide it, or only talk about it. Both channels are asked the same question:
    # do they respond to the directive, or only to the trait being named? Every
    # range below excludes the inert model, which is reported separately; a
    # range spanning it would make a flat control look like a ceiling.
    if stated and stated_base:
        base = {r["model"]: r for r in stated_base}
        bym: dict[str, dict] = {}
        for r in stated:
            bym.setdefault(r["model"], {})[r["persona"]] = r
        # "Responsive" is defined on the DATA, not by naming a model: a model
        # whose three directive cells all sit within a hair of 0.5 has not
        # answered the battery, and averaging it into a range hides that.
        def _flat(cells: dict) -> bool:
            v = [cells[c]["stated_cautiousness"] for c in (GENUINE, CONCEALED, VERBAL)]
            return max(abs(x - 0.5) for x in v) < 0.1

        inert = sorted(m for m, c in bym.items() if _flat(c))
        resp = sorted(m for m in bym if m not in inert)
        out.append(_cmd("StatedNModels", str(len(bym))))
        out.append(_cmd("StatedNResponsive", str(len(resp))))
        out.append(_cmd("StatedNItems", str(stated[0]["n_items"])))
        for label, cond in (("Have", GENUINE), ("Hide", CONCEALED), ("Fake", VERBAL)):
            v = [bym[m][cond]["stated_cautiousness"] for m in resp]
            out.append(_cmd(f"Stated{label}Lo", f"{min(v):.3f}"))
            out.append(_cmd(f"Stated{label}Hi", f"{max(v):.3f}"))
        bv = [base[m]["stated_cautiousness"] for m in bym if m in base]
        out.append(_cmd("StatedBaseLo", f"{min(bv):.3f}"))
        out.append(_cmd("StatedBaseHi", f"{max(bv):.3f}"))
        if inert:
            iv = [bym[inert[0]][c]["stated_cautiousness"]
                  for c in (GENUINE, CONCEALED, VERBAL)]
            out.append(_cmd("StatedInertModel", inert[0].split("/")[-1]))
            out.append(_cmd("StatedInertLo", f"{min(iv):.3f}"))
            out.append(_cmd("StatedInertHi", f"{max(iv):.3f}"))
            out.append(_cmd("StatedInertBase",
                            f"{base[inert[0]]['stated_cautiousness']:.3f}"))
        # The worst-scored cell, so the footnote naming it cannot go stale.
        n_full = max(r["n_scored"] for r in stated)
        worst = min(stated, key=lambda r: (r["n_scored"], r["mean_answer_mass"]))
        out.append(_cmd("StatedNScored", str(n_full)))
        out.append(_cmd("StatedWorstModel", worst["model"].split("/")[-1]))
        out.append(_cmd("StatedWorstCond", worst["persona"].replace("cautious-", "")))
        out.append(_cmd("StatedWorstScored", str(worst["n_scored"])))
        out.append(_cmd("StatedWorstMass", f"{worst['mean_answer_mass']:.2f}"))

    if revealed:
        rows = {r["model"]: r for r in revealed["arms"]["R"]}
        good = [r for r in revealed["arms"]["R"] if r.get("specific")]
        cov = revealed["coverage"]
        out.append(_cmd("RevNModels", str(cov["models_total"])))
        out.append(_cmd("RevNTriad", str(cov["models_with_complete_R_triad"])))
        out.append(_cmd("RevNInterp", str(len(good))))
        out.append(_cmd("RevSpecMargin",
                        f"{revealed['specificity_margin_required']:.2f}"))
        gaps = [r["scores"][CONCEALED] - r["scores"][VERBAL] for r in good]
        margins = [r["scores"][CONCEALED] - r["scores"][UNRELATED] for r in good]
        out.append(_cmd("RevGapLo", f"{min(gaps):+.3f}"))
        out.append(_cmd("RevGapHi", f"{max(gaps):+.3f}"))
        out.append(_cmd("RevSpecLo", f"{min(margins):+.2f}"))
        out.append(_cmd("RevSpecHi", f"{max(margins):+.2f}"))
        # The model that fails the specificity gate: a control that behaved like
        # a control, and it must be quotable as such rather than as missing data.
        failed = [r for r in revealed["arms"]["R"]
                  if r.get("specific") is False]
        if failed:
            f = failed[0]
            out.append(_cmd("RevInertModel", _norm(f["model"]).split("/")[-1]))
            out.append(_cmd("RevInertMargin",
                            f"{f['scores'][CONCEALED] - f['scores'][UNRELATED]:+.3f}"))
            out.append(_cmd("RevInertGap",
                            f"{f['scores'][CONCEALED] - f['scores'][VERBAL]:+.3f}"))
        # Pairs dropped because the model put no mass on either option label.
        drop = max(rows.values(), key=lambda r: r.get("n_unscorable", 0))
        if drop.get("n_unscorable"):
            out.append(_cmd("RevDropModel", _norm(drop["model"]).split("/")[-1]))
            out.append(_cmd("RevDropPairs", str(drop["n_unscorable"])))
            out.append(_cmd("RevKeptPairs", str(drop["n_pairs"])))
        # The content control: displacement that reproduces on invented outcomes
        # is style, not preference. Only one model has the cell; say so.
        inv = [r for r in revealed["arms"]["N_minus"]
               if r["computable"] and _norm(r["model"]) in
               {_norm(g["model"]) for g in good}]
        out.append(_cmd("RevNInvented", str(len(inv))))
        if inv:
            i = inv[0]
            out.append(_cmd("RevInventedModel", _norm(i["model"]).split("/")[-1]))
            out.append(_cmd("RevInventedConcealed", f"{i['scores'][CONCEALED]:+.3f}"))
            out.append(_cmd("RevInventedVerbal", f"{i['scores'][VERBAL]:+.3f}"))
            out.append(_cmd("RevInventedGap",
                            f"{i['scores'][CONCEALED] - i['scores'][VERBAL]:+.3f}"))

    # The scaling claim under length matching. The paper already reports that
    # the MEAN residual survives the length control (+0.021 vs +0.025). That is
    # a different question from whether the SCALING result survives it, and the
    # answer is not the same: pooled, the size correlation nearly vanishes.
    # Emitted here so the paper cannot report the reassuring half alone.
    if length and length.get("matched_band", {}).get("per_model"):
        import math as _m
        pm = length["matched_band"]["per_model"]
        sizes_, _f = _roster_sizes()
        pairs_ = [(sizes_[m], v["residual"]) for m, v in pm.items() if m in sizes_]

        def _c(xs, ys):
            n_ = len(xs)
            mx, my = sum(xs) / n_, sum(ys) / n_
            sx = _m.sqrt(sum((x - mx) ** 2 for x in xs))
            sy = _m.sqrt(sum((y - my) ** 2 for y in ys))
            return None if sx == 0 or sy == 0 else sum(
                (x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)

        if len(pairs_) >= 4:
            out.append(_cmd("MatchedPooledCorr",
                            f"{_c([_m.log2(a) for a, _ in pairs_], [b for _, b in pairs_]):+.2f}"))
        qp = sorted([(sizes_[m], v["residual"]) for m, v in pm.items()
                     if m.startswith("Qwen/Qwen3.5-")], key=lambda t: t[0])
        if len(qp) >= 3:
            out.append(_cmd("MatchedWithinCorr",
                            f"{_c([_m.log2(a) for a, _ in qp], [b for _, b in qp]):+.2f}"))
            out.append(_cmd("MatchedLadderFall", f"{qp[-1][1] - qp[0][1]:+.3f}"))
            out.append(_cmd("MatchedLadderSmallResid", f"{qp[0][1]:+.3f}"))
            out.append(_cmd("MatchedLadderLargeResid", f"{qp[-1][1]:+.3f}"))
        # How far individual models move, since the stable mean hides it.
        deltas = [(m, v["residual"]) for m, v in pm.items()]
        card_v = {t["model"]: t["value"] for t in tiles}
        moves = [(m, r - card_v[m]) for m, r in deltas if m in card_v]
        if moves:
            big = max(moves, key=lambda t: abs(t[1]))
            out.append(_cmd("MatchedBiggestMover", big[0].split("/")[-1]))
            out.append(_cmd("MatchedBiggestMove", f"{big[1]:+.3f}"))
            out.append(_cmd("MatchedNGrow", str(sum(1 for _, d in moves if d > 0))))
            out.append(_cmd("MatchedNModels", str(len(moves))))

    # The neutral-option control. Emitted only when all four cells exist, so
    # the paper cannot quote half of it: a P(C) without the matching coherence
    # comparison would be an interesting number standing in for the control it
    # is not.
    # The JSON now holds every model; macros quote the model with the largest
    # opt-out gap plus the across-model spread, because a single model's
    # numbers in the prose stopped being the whole result at n>1.
    nmods = [m for m in (neutral or {}).get("models", [])
             if m.get("floor_shift") is not None]
    if nmods:
        lead = max(nmods, key=lambda m: m.get("opt_out_gap") or 0)
        shifts = [m["floor_shift"] for m in nmods]
        gaps = [m["opt_out_gap"] for m in nmods if m.get("opt_out_gap") is not None]
        out.append(_cmd("NeutNModels", str(len(nmods))))
        # Counted from the arms actually present, not 2x the model count: a
        # model can reach this list with one arm complete and one still queued,
        # and the ledger quoted a hand-multiplied cell count that went stale
        # exactly that way.
        out.append(_cmd("NeutNCells", str(sum(
            1 for m in nmods for a in m.get("arms", {}).values()
            if a.get("neutral", {}).get("usable")))))
        out.append(_cmd("NeutShiftLo", f"{min(shifts):+.3f}"))
        out.append(_cmd("NeutShiftHi", f"{max(shifts):+.3f}"))
        interp = [m for m in nmods if m.get("interpretable")]
        ishifts = [m["floor_shift"] for m in interp]
        out.append(_cmd("NeutNInterp", str(len(interp))))
        out.append(_cmd("NeutNRefuse", str(len(nmods) - len(interp))))
        if ishifts:
            out.append(_cmd("NeutIShiftLo", f"{min(ishifts):+.3f}"))
            out.append(_cmd("NeutIShiftHi", f"{max(ishifts):+.3f}"))
            out.append(_cmd("NeutNSurvive",
                            str(sum(1 for s_ in ishifts if abs(s_) < 0.05))))
        abs_ = [m["arms"]["N_minus"]["neutral"]["mean_ab_mass"] for m in nmods
                if m["arms"]["N_minus"]["neutral"].get("mean_ab_mass") is not None]
        refuse_ab = [m["arms"]["N_minus"]["neutral"]["mean_ab_mass"]
                     for m in nmods if not m.get("interpretable")]
        if refuse_ab:
            out.append(_cmd("NeutABRefuseHi", f"{max(refuse_ab):.4f}"))
            out.append(_cmd("NeutABRefuseLo", f"{min(refuse_ab):.4f}"))
        if abs_:
            out.append(_cmd("NeutABHi", f"{max(abs_):.3f}"))
        if gaps:
            out.append(_cmd("NeutGapLo", f"{min(gaps):+.3f}"))
            out.append(_cmd("NeutGapHi", f"{max(gaps):+.3f}"))
            out.append(_cmd("NeutNGapPositive", str(sum(1 for g in gaps if g > 0))))
        neutral = lead
        arms = neutral["arms"]

        def _g(arm, inst, field):
            s = arms.get(arm, {}).get(inst)
            return s.get(field) if s and s.get("usable") else None

        out.append(_cmd("NeutModel", neutral["model"].split("/")[-1]))
        out.append(_cmd("NeutResidBinary", f"{neutral['residual_binary']:+.3f}"))
        out.append(_cmd("NeutResidNeutral", f"{neutral['residual_neutral']:+.3f}"))
        out.append(_cmd("NeutFloorShift", f"{neutral['floor_shift']:+.3f}"))
        for arm, tag in (("R", "Real"), ("N_minus", "Inv")):
            for inst, itag in (("binary", "Bin"), ("neutral", "Neut")):
                v = _g(arm, inst, "coherence")
                if v is not None:
                    out.append(_cmd(f"NeutCoh{tag}{itag}", f"{v:.3f}"))
            pc = _g(arm, "neutral", "mean_p_neither")
            if pc is not None:
                out.append(_cmd(f"NeutPC{tag}", f"{pc:.3f}"))
                out.append(_cmd(f"NeutPCPct{tag}", f"{100 * pc:.0f}"))
            maj = _g(arm, "neutral", "frac_neither_majority")
            if maj is not None:
                out.append(_cmd(f"NeutMaj{tag}", f"{100 * maj:.0f}"))

    if personas:
        vals = [r["floor_corrected"] for r in personas]
        out.append(_cmd("NPersonaCells", str(len(vals))))
        out.append(_cmd("NPersonaModels", str(len({r["model"] for r in personas}))))
        out.append(_cmd("PersonaAbovePointThree", str(sum(1 for v in vals if v > 0.3))))
        out.append(_cmd("PersonaMax", f"{max(vals):+.2f}"))
        out.append(_cmd("PersonaMin", f"{min(vals):+.2f}"))
        # D1 vs D2: the spread attributable to WHERE the trait sits, against
        # the spread attributable to WHICH trait it is. If the first is the
        # smaller, depth is not the interesting variable.
        def _spread_over(varying: str) -> float:
            """Mean within-group range when `varying` is the only thing that moves.

            Groups are keyed by everything *except* `varying`, so each group
            holds the same model under the same other factor and differs only
            in the one under test.
            """
            held = "depth" if varying == "persona" else "persona"
            groups: dict[tuple, list[float]] = {}
            for r in personas:
                groups.setdefault((r["model"], r[held]), []).append(r["floor_corrected"])
            return sum(max(v) - min(v) for v in groups.values()) / len(groups)

        out.append(_cmd("DepthSpread", f"{_spread_over('depth'):.3f}"))
        out.append(_cmd("PersonaSpread", f"{_spread_over('persona'):.3f}"))

    # Surface covariates: how much of each arm's ordering is length, numerals
    # and vocabulary, and what survives projecting them out. Also the battery's
    # own comparability, which is a property of the stimuli and is measured
    # before any model is consulted.
    if surface and surface.get("summary"):
        arms = {"R": "R", "N_plus": "Np", "N_minus": "Nm"}
        for arm, tag in arms.items():
            s = surface["summary"].get(arm)
            if not s:
                continue
            out.append(_cmd(f"Surf{tag}Rsq", f"{s['surface_r2_mean']:.3f}"))
            for stat, key in (("PCOne", "pc1"), ("Corr", "cross_model_r")):
                for when, suffix in (("Raw", "_raw"), ("Ctrl", "_controlled")):
                    v = s.get(f"{key}{suffix}")
                    if v is not None:
                        out.append(_cmd(f"Surf{tag}{stat}{when}", f"{v:.3f}"))

        comp = surface.get("battery_comparability", {})
        for arm, tag in arms.items():
            c = comp.get(arm)
            if not c:
                continue
            out.append(_cmd(f"Bat{tag}Chars", f"{c['chars']:.1f}"))
            out.append(_cmd(f"Bat{tag}Words", f"{c['words']:.2f}"))
            out.append(_cmd(f"Bat{tag}Unique", str(c["n_unique_texts"])))
            out.append(_cmd(f"Bat{tag}RatioMean", f"{c['length_ratio_mean']:.3f}"))
            out.append(_cmd(f"Bat{tag}RatioMax", f"{c['length_ratio_max']:.2f}"))
            out.append(_cmd(f"Bat{tag}Longer", str(c["n_longer_than_real"])))
            out.append(_cmd(f"Bat{tag}Outside", str(c["n_outside_stated_bound"])))
            out.append(_cmd(f"Bat{tag}PctNumeral",
                            f"{100 * c['frac_with_numeral']:.1f}"))
        if "R" in comp and "N_minus" in comp:
            gap = 100 * (comp["N_minus"]["chars"] / comp["R"]["chars"] - 1)
            out.append(_cmd("BatCharGapPct", f"{gap:.1f}"))
            wgap = 100 * (comp["N_minus"]["words"] / comp["R"]["words"] - 1)
            out.append(_cmd("BatWordGapPct", f"{wgap:.1f}"))
        tl = surface.get("token_lengths") or {}
        if tl:
            gaps = [t["n_minus_vs_r_pct"] for t in tl.values()
                    if "n_minus_vs_r_pct" in t]
            out.append(_cmd("TokGapLo", f"{min(gaps):.0f}"))
            out.append(_cmd("TokGapHi", f"{max(gaps):.0f}"))
            out.append(_cmd("TokNTokenisers", str(len(gaps))))

        if surface.get("seeds"):
            nf = [a.get("n_features_used") for s in surface["seeds"].values()
                  for name, a in s.items() if name == "N_minus"]
            if nf:
                out.append(_cmd("SurfNmFeatures", str(min(nf))))
                out.append(_cmd("SurfFeatures", str(len(surface["features"]))))

    # Differential attrition: the answer-mass gate keeps a different sample on
    # each arm, so the matched-pair residual is the one that is not confounded
    # with what the gate happened to retain.
    if attrition and attrition.get("summary"):
        s = attrition["summary"]
        out.append(_cmd("AttrNCells", str(s["n_cells"])))
        out.append(_cmd("AttrNAffected", str(s["n_cells_with_attrition"])))
        out.append(_cmd("AttrResidRaw", f"{s['mean_residual_raw']:+.4f}"))
        out.append(_cmd("AttrResidMatched", f"{s['mean_residual_matched']:+.4f}"))
        out.append(_cmd("AttrShift", f"{s['mean_residual_shift']:+.4f}"))
        out.append(_cmd("AttrMaxShift", f"{s['max_abs_residual_shift']:.4f}"))
        out.append(_cmd("AttrWorstDiffPP",
                        f"{100 * s['worst_differential_attrition']:.1f}"))
        out.append(_cmd("AttrFloor", f"{attrition['answer_mass_floor']:.1f}"))
        sweep = attrition.get("floor_sweep") or []
        if sweep:
            lo = [r for r in sweep if r["floor"] == min(r2["floor"] for r2 in sweep)]
            hi = [r for r in sweep if r["floor"] == max(r2["floor"] for r2 in sweep)]
            if lo and hi:
                out.append(_cmd("AttrResidNoGate",
                                f"{sum(r['residual_matched'] for r in lo)/len(lo):+.4f}"))
                out.append(_cmd("AttrResidStrictGate",
                                f"{sum(r['residual_matched'] for r in hi)/len(hi):+.4f}"))

    # The prompt factor. Two wordings, everything else held fixed.
    if contrast and contrast.get("by_prompt"):
        bp = contrast["by_prompt"]
        out.append(_cmd("PcNModels", str(len({c["model"] for c in contrast["cells"]}))))
        for pid, tag in (("ue", "Ue"), ("v2", "Vtwo")):
            if pid in bp:
                out.append(_cmd(f"Pc{tag}Residual", f"{bp[pid]['mean_residual']:+.4f}"))
                out.append(_cmd(f"Pc{tag}ConvR", f"{bp[pid]['mean_conviction_R']:.3f}"))
                out.append(_cmd(f"Pc{tag}ConvN", f"{bp[pid]['mean_conviction_N_minus']:.3f}"))
        if "ue" in bp and "v2" in bp:
            out.append(_cmd("PcResidualShift",
                            f"{abs(bp['ue']['mean_residual'] - bp['v2']['mean_residual']):.4f}"))
        # Per model, because the mean hides that one model reverses.
        for c in contrast["cells"]:
            short = _slug(c["model"].split("/")[-1])
            tag = "Ue" if c["prompt"] == "ue" else "Vtwo"
            out.append(_cmd(f"Pc{short}{tag}Resid", f"{c['residual']:+.4f}"))
            out.append(_cmd(f"Pc{short}{tag}ConvR", f"{c['conviction_R']:.3f}"))
            out.append(_cmd(f"Pc{short}{tag}ConvN", f"{c['conviction_N_minus']:.3f}"))

    # Avoidance: when gibberish beats a real outcome, which real outcome was it?
    # The answer decides whether content-blindness is total (confusion) or
    # whether the model reads well enough to rank nonsense above bad outcomes.
    if avoidance and avoidance.get("models"):
        ms = avoidance["models"]
        out.append(_cmd("AvoidNModels", str(len(ms))))
        cs = [m["spearman_utility_vs_prefer_real"] for m in ms
              if m["spearman_utility_vs_prefer_real"] is not None]
        if cs:
            out.append(_cmd("AvoidCorrLo", f"{min(cs):+.3f}"))
            out.append(_cmd("AvoidCorrHi", f"{max(cs):+.3f}"))
        pcts = [m["median_utility_percentile_of_losers"] for m in ms
                if m["median_utility_percentile_of_losers"] is not None]
        if pcts:
            out.append(_cmd("AvoidPctileLo", f"{min(pcts):.0f}"))
            out.append(_cmd("AvoidPctileHi", f"{max(pcts):.0f}"))
            out.append(_cmd("AvoidNModelsWithFlips", str(len(pcts))))
        t = avoidance.get("totals") or {}
        if t:
            out.append(_cmd("AvoidFlipsRaw", _thousands(t["n_flips_raw"])))
            out.append(_cmd("AvoidFlipsRobust", str(t["n_flips_robust"])))
            out.append(_cmd("AvoidFlipsPct", f"{100 * t['frac_robust']:.0f}"))
            out.append(_cmd("AvoidNoFlipModels", str(t["n_models_with_no_robust_flip"])))
            out.append(_cmd("AvoidNPairsTotal", _thousands(t["n_pairs"])))
        conc = avoidance.get("cross_model_concordance")
        if conc is not None:
            out.append(_cmd("AvoidConcordance", f"{conc:+.3f}"))
        cat = avoidance.get("mean_category_loss_rate") or {}
        if cat:
            top = max(cat.items(), key=lambda kv: kv[1])
            out.append(_cmd("AvoidTopCategory", top[0]))
            out.append(_cmd("AvoidTopRate", f"{100 * top[1]:.1f}"))

    return "".join(out)


def build_stated_table(stated: list[dict], stated_base: list[dict]) -> str:
    """Track 3, stated channel: self-reported cautiousness under each directive.

    The no-premise column is the whole point of the table. Without it, 0.87-1.00
    under every directive reads as "these models are cautious"; with it, the same
    numbers read as "any mention of the trait moves the report to ceiling, and
    the directive attached to it does not move it back".
    """
    base = {r["model"]: r["stated_cautiousness"] for r in stated_base}
    bym: dict[str, dict] = {}
    for r in stated:
        bym.setdefault(r["model"], {})[r["persona"]] = r
    rows = []
    for model in sorted(bym, key=lambda m: -bym[m][GENUINE]["stated_cautiousness"]):
        cells = bym[model]
        # A cell scored on fewer items than the rest is marked, not hidden.
        n_full = max(r["n_scored"] for r in stated)
        def _f(cond: str) -> str:
            r = cells[cond]
            mark = r"$^{\dagger}$" if r["n_scored"] < n_full else ""
            return f"{r['stated_cautiousness']:.3f}{mark}"
        b = f"{base[model]:.3f}" if model in base else "--"
        # Escaped outside the f-string: a backslash inside one is a syntax
        # error before 3.12, and pyproject declares >=3.11.
        name = model.split("/")[-1].replace("_", r"\_")
        rows.append(f"\\texttt{{{name}}} & "
                    f"{b} & {_f(GENUINE)} & {_f(CONCEALED)} & {_f(VERBAL)}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        "\\begin{tabular}{@{}lrrrr@{}}\n"
        "\\toprule\n"
        "model & no premise & told to have & told to hide & told to fake \\\\\n"
        "\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def build_revealed_table(revealed: dict) -> str:
    """Track 3, revealed channel: alignment with the genuine-persona template.

    Columns are ordered detection, false positive, gap -- so the gap is read
    next to the denominator that makes it mean anything -- and the specificity
    control sits last as the gate on whether the row is interpretable at all.
    """
    rows = []
    for r in revealed["arms"]["R"]:
        name = _norm(r["model"]).split("/")[-1].replace("_", r"\_")
        if not r["computable"]:
            missing = ", ".join(m.replace("cautious-", "") for m in r["missing"])
            rows.append(f"\\texttt{{{name}}} & \\multicolumn{{4}}{{c}}{{"
                        f"\\emph{{no data: {missing} cells not collected}}}} & --")
            continue
        s = r["scores"]
        verdict = ("pass" if r.get("specific") else
                   "\\textbf{fail}" if r.get("specific") is False else "--")
        rows.append(
            f"\\texttt{{{name}}} & {s[CONCEALED]:+.3f} & {s[VERBAL]:+.3f} & "
            f"{s[CONCEALED] - s[VERBAL]:+.3f} & {s[UNRELATED]:+.3f} & {verdict}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        "\\begin{tabular}{@{}lrrrrl@{}}\n"
        "\\toprule\n"
        "model & concealed & verbal (FPR) & gap & \\emph{ambitious} & "
        "specific? \\\\\n"
        "\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def build_comply_table(comply: dict) -> str:
    """The directive arms: both commands, per model, with the verdict.

    Same reason as every other generated table here -- the two directive columns
    differ by one letter and their interpretation depends on which of them
    agrees with the model's own baseline, which is exactly the kind of thing a
    hand-typed table gets subtly wrong.
    """
    dirs = {d["model"]: d for d in comply.get("direction_control", [])}
    rows = []
    for r in sorted(comply["rows"], key=lambda r: -(r.get("baseline_mean_p_a") or 0)):
        d = dirs.get(r["model"])
        if not d:
            continue
        name = r["model"].split("/")[-1].replace("_", r"\_")
        # The verdict word only; the sentence lives in the prose.
        verdict = d["verdict"].split(" -- ")[0]
        rows.append(
            f"\\texttt{{{name}}} & {r['baseline_mean_p_a']:.3f} & {d['leans']} & "
            f"{d['p_a_under_answer_a']:.3f} & {d['p_a_under_answer_b']:.3f} & "
            f"{r['persona_displacement']:.3f} & "
            f"{r['directive_displacement']:.3f} & {verdict}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        # Eight columns including a verdict phrase; at \normalsize this runs
        # ~32pt into the right margin.
        "\\small\n\\begin{tabular}{@{}lrcrrrrl@{}}\n\\toprule\n"
        "model & $P(A)$ & leans & \\multicolumn{2}{c}{told to answer} & "
        "\\multicolumn{2}{c}{displacement} & verdict \\\\\n"
        "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\n"
        " & base & & A & B & persona & directive & \\\\\n\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n\\bottomrule\n\\end{tabular}\n")


def build_neutral_table(neutral: dict) -> str:
    """Track the neutral-option control: one block per model, both instruments.

    Generated because the first draft of this table had hand-typed decisive
    fractions in it -- the exact thing numbers.tex exists to prevent, written
    by the same person who wrote the rule.
    """
    models = [m for m in neutral["models"] if m.get("floor_shift") is not None]
    rows = []
    for m in sorted(models, key=lambda m: -(m.get("opt_out_gap") or 0)):
        name = m["model"].split("/")[-1].replace("_", r"\_")
        for arm, tag in (("R", r"\armR{}"), ("N_minus", r"\armNm{}")):
            for inst, label in (("binary", "forced binary"),
                                ("neutral", "neutral option")):
                c = m["arms"][arm][inst]
                pc = c.get("mean_p_neither")
                rows.append(
                    f"\\texttt{{{name}}} & {tag} & {label} & "
                    f"{c['coherence']:.3f} & {c['decisive_fraction'] * 100:.1f}\\% & "
                    f"{(f'{pc:.3f}' if pc is not None else '---')}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        "\\begin{tabular}{@{}lllrrr@{}}\n\\toprule\n"
        "model & arm & instrument & coherence & decisive & $P(\\text{neither})$ \\\\\n"
        "\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n"
        "\\bottomrule\n\\end{tabular}\n")


def build_table(card: dict) -> str:
    r"""Table 1 as a complete \input-able tabular.

    Generated for the same reason as the macros: a table maintained by hand
    beside a card that is rebuilt nightly diverges, and the divergence is
    invisible in a compiled PDF.

    The whole environment is emitted, not just the body rows, for two reasons.
    A file of bare rows ending in ``\\`` cannot be followed by ``\bottomrule``
    in the parent file --- ``\\`` scans ahead for its optional ``[dim]``
    argument, that scan runs off the end of the \input, and the rule is then
    read outside a row boundary and fails as "Misplaced \noalign" pointing at
    the wrong file. Emitting the environment also means the column
    specification lives in one place instead of being repeated, and kept in
    sync by hand, in both main.tex and slides.tex.
    """
    tiles = [t for t in card["tiles"] if t["badge"] == "FLOOR_CORRECTED"]
    tiles.sort(key=lambda t: -t["raw_coherence"])
    rows = []
    for t in tiles:
        dnf = t.get("design_noise_floor")
        if t.get("clears_floor") is None:
            clears = "--"
        elif not t["clears_floor"]:
            clears = "no"
        elif dnf is not None and dnf < 0.005:
            # A ratio against a near-zero denominator is a division artifact,
            # not a large effect; flag it instead of printing a big number.
            clears = r"$>$\,floor$^{*}$"
        else:
            clears = f"{t['floor_margin']:.1f}$\\times$"
        name = t["model"].replace("_", r"\_")
        rows.append(
            f"\\texttt{{{name}}} & "
            f"{t['raw_coherence']:.3f} & {t['floor']:.3f} & {t['value']:+.3f} & "
            f"{(f'{dnf:.3f}' if dnf is not None else '--')} & {clears} & "
            f"{t['decisive_fraction']['R'] * 100:.1f}\\% & "
            f"{t['decisive_fraction']['N_minus'] * 100:.1f}\\%"
        )
    header = (r"model & R & N\textsuperscript{--} & R$-$N\textsuperscript{--}"
              r" & floor & clears & dec.\ R & dec.\ N\textsuperscript{--}")
    return (
        "% Generated by scripts/paper_numbers.py. Do not edit.\n"
        "\\begin{tabular}{@{}lrrrrlrr@{}}\n"
        "\\toprule\n"
        f"{header} \\\\\n"
        "\\midrule\n"
        + " \\\\\n".join(rows) + " \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--card", default="card.json")
    ap.add_argument("--personas", default="site/persona_depth.json")
    ap.add_argument("--out", default="paper/numbers.tex")
    ap.add_argument("--table-out", default="paper/table_main.tex")
    ap.add_argument("--length", default="site/length_control.json")
    ap.add_argument("--floor-decomp", default="site/floor_decomposition.json")
    ap.add_argument("--reasoning", default="site/reasoning_effect.json")
    ap.add_argument("--validity", default="site/persona_validity.json")
    ap.add_argument("--detector", default="site/nonsense_detector.json")
    ap.add_argument("--stated", default="self_report_summary_personas.json")
    ap.add_argument("--stated-base", default="self_report_summary.json")
    ap.add_argument("--revealed", default="site/deception.json")
    ap.add_argument("--neutral", default="site/neutral_control.json")
    ap.add_argument("--rendered", default="site/rendered_prompts.json")
    ap.add_argument("--comply", default="site/comply_gate.json")
    ap.add_argument("--mixed", default="site/mixed_arm.json")
    ap.add_argument("--hosted-card", default="site/card_hosted.json")
    ap.add_argument("--avoidance", default="site/avoidance.json")
    ap.add_argument("--prompt-contrast", default="site/prompt_contrast.json")
    ap.add_argument("--surface", default="site/surface_covariates.json")
    ap.add_argument("--attrition", default="site/attrition_control.json")
    ap.add_argument("--harm", default="site/harm_residual.json")
    ap.add_argument("--stated-table-out", default="paper/table_stated.tex")
    ap.add_argument("--revealed-table-out", default="paper/table_revealed.tex")
    ap.add_argument("--neutral-table-out", default="paper/table_neutral.tex")
    ap.add_argument("--comply-table-out", default="paper/table_comply.tex")
    args = ap.parse_args()

    card = json.loads(Path(args.card).read_text())
    ppath = Path(args.personas)
    personas = json.loads(ppath.read_text()) if ppath.exists() else []

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lpath = Path(args.length)
    length = json.loads(lpath.read_text()) if lpath.exists() else None
    if length is None:
        print(f"  no length control at {lpath}; omitting those macros")
    fdpath = Path(args.floor_decomp)
    floor_decomp = json.loads(fdpath.read_text()) if fdpath.exists() else None
    rpath = Path(args.reasoning)
    reasoning = json.loads(rpath.read_text()) if rpath.exists() else None
    vpath = Path(args.validity)
    validity = json.loads(vpath.read_text()) if vpath.exists() else None
    dpath = Path(args.detector)
    detector = json.loads(dpath.read_text()) if dpath.exists() else None
    # Track 3 inputs. Each is optional in the same way the others are: the
    # macros are simply not emitted, and lint_paper.py then fails loudly on the
    # subsection that uses them rather than the paper compiling with blanks.
    spath, sbpath, rpath3 = (Path(args.stated), Path(args.stated_base),
                             Path(args.revealed))
    stated = json.loads(spath.read_text()) if spath.exists() else None
    stated_base = json.loads(sbpath.read_text()) if sbpath.exists() else None
    revealed = json.loads(rpath3.read_text()) if rpath3.exists() else None
    npath = Path(args.neutral)
    neutral = json.loads(npath.read_text()) if npath.exists() else None
    for label, obj, path in (("stated self-report", stated, spath),
                             ("self-report baseline", stated_base, sbpath),
                             ("revealed channel", revealed, rpath3)):
        if obj is None:
            print(f"  no {label} at {path}; omitting those macros")
    rpath4 = Path(args.rendered)
    rendered = json.loads(rpath4.read_text()) if rpath4.exists() else None
    cpath = Path(args.comply)
    comply = json.loads(cpath.read_text()) if cpath.exists() else None
    mpath = Path(args.mixed)
    mixed = json.loads(mpath.read_text()) if mpath.exists() else None
    hpath = Path(args.harm)
    harm = json.loads(hpath.read_text()) if hpath.exists() else None
    if mixed is not None and harm is not None:
        mixed = dict(mixed, harm=harm)
    if rendered is None:
        print(f"  no rendered prompts at {rpath4}; omitting harness macros")
    pcpath = Path(args.prompt_contrast)
    contrast = json.loads(pcpath.read_text()) if pcpath.exists() else None
    avpath = Path(args.avoidance)
    avoidance = json.loads(avpath.read_text()) if avpath.exists() else None
    hcpath = Path(args.hosted_card)
    hosted = json.loads(hcpath.read_text()) if hcpath.exists() else None
    sfpath, atpath = Path(args.surface), Path(args.attrition)
    surface = json.loads(sfpath.read_text()) if sfpath.exists() else None
    attrition = json.loads(atpath.read_text()) if atpath.exists() else None
    for label, obj, path in (("surface covariates", surface, sfpath),
                             ("attrition control", attrition, atpath)):
        if obj is None:
            print(f"  no {label} at {path}; omitting those macros")
    text = build(card, personas, length, floor_decomp, reasoning, validity,
                 detector, stated, stated_base, revealed, neutral, rendered,
                 comply, mixed, surface, attrition, hosted, avoidance,
                 contrast)
    out.write_text(text)
    print(f"wrote {out}  ({text.count('newcommand')} macros)")

    tout = Path(args.table_out)
    tout.write_text(build_table(card))
    print(f"wrote {tout}")

    if stated and stated_base:
        stout = Path(args.stated_table_out)
        stout.write_text(build_stated_table(stated, stated_base))
        print(f"wrote {stout}")
    if neutral and neutral.get("models"):
        ntout = Path(args.neutral_table_out)
        ntout.write_text(build_neutral_table(neutral))
        print(f"wrote {ntout}")
    if comply and comply.get("direction_control"):
        ctout = Path(args.comply_table_out)
        ctout.write_text(build_comply_table(comply))
        print(f"wrote {ctout}")
    if revealed:
        rtout = Path(args.revealed_table_out)
        rtout.write_text(build_revealed_table(revealed))
        print(f"wrote {rtout}")


if __name__ == "__main__":
    main()
