"""Measure per-model sweep throughput from completed cells -> throughput.json.

So the sweep can tell you how long it will take before you commit to it, using
what this roster actually did rather than a guess. Regenerate whenever new
cells land; the estimate improves as the project grows.

    python3 scripts/throughput.py

Reads the `.done` sidecars, which carry n_rows and wall_s for every cell that
exited cleanly. Aborted cells are included: they were real work at a real rate.
"""

from __future__ import annotations

import argparse
import json
import statistics as st
from pathlib import Path

EXPECTED_ROWS = 5000


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="throughput.json")
    args = ap.parse_args()

    rates: dict[str, list[float]] = {}
    for p in sorted(Path(args.results).glob("*.jsonl.done")):
        try:
            d = json.loads(p.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        n, w = d.get("n_rows"), d.get("wall_s")
        if n and w and w > 0:
            rates.setdefault(d["model"], []).append(n / w)

    if not rates:
        print("no usable sidecars; not writing")
        return

    # Median, not mean: one cold container or one contended GPU should not set
    # the estimate for the whole model.
    table = {m: round(st.median(v), 2) for m, v in sorted(rates.items())}
    counts = {m: len(v) for m, v in rates.items()}
    allr = [r for v in rates.values() for r in v]

    out = {
        "_comment": "rows/second per model, median over completed cells. "
                    "Generated by scripts/throughput.py; read by modal_app/sweep.py "
                    "to print an ETA before the GPU wave.",
        "rows_per_s": table,
        "cells_measured": counts,
        "default_rows_per_s": round(st.median(allr), 2),
        # Container start + weight download/load, before the first row lands.
        # Measured from the gap between launch and first checkpoint; generous
        # on purpose, since an ETA that runs under is worse than one that runs
        # over.
        "cold_start_s": 150,
    }
    Path(args.out).write_text(json.dumps(out, indent=2) + "\n")

    print(f"{'model':34s}{'cells':>6s}{'rows/s':>9s}{'per cell':>10s}")
    for m, r in sorted(table.items(), key=lambda kv: -kv[1]):
        print(f"{m[:33]:34s}{counts[m]:>6d}{r:>9.1f}"
              f"{EXPECTED_ROWS / r / 60:>9.1f}m")
    print(f"\ndefault {out['default_rows_per_s']} rows/s, "
          f"cold start {out['cold_start_s']}s")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
